[package]
name = "sce_parser"
version = "0.3.3"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
getrandom = { version = "0.2.16", default-features = false, features = ["js"] }
