[package]
name = "sce_parser"
version = "0.3.0"
edition = "2021"
authors = ["you <you@example.com>"]
description = "SCE parser for browser (WASM) - fetch + parse"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# wasm bindings
wasm-bindgen = "0.2.104"
wasm-bindgen-futures = "0.4"

# browser fetch / DOM
web-sys = { version = "0.3.76", features = [
  "Window", "Response", "Request", "RequestInit", "RequestMode",
  "Headers", "console", "DomException", "Url", "Document"
] }
js-sys = "0.3"

# HTML parser
scraper = "0.18"

# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# small utilities
regex = { version = "1.10", default-features = false, features = ["std"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

