[package]
name = "sce_parser"
version = "0.2.4"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# wasm bindings
wasm-bindgen = "0.2.104"

# HTML parser
scraper = "0.18"

# JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# regex (lightweight)
regex = { version = "1.10", default-features = false, features = ["std", "unicode"] }

# helper
once_cell = "1.21"

# NOTE:
# getrandom is required by some transitive deps. Enable wasm feature only for wasm target below.
# This avoids compile errors on wasm32 where getrandom needs wasm_js backend.
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
