[package]
name = "sce_parser"
version = "0.3.3"
edition = "2021"
description = "SCE Parser compiled to WebAssembly"
license = "MIT"
repository = "https://github.com/yourname/sce_parser"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Основные зависимости
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"

# Поддержка случайных чисел и getrandom для WebAssembly
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
getrandom = { version = "0.2.16", default-features = false, features = ["js"] }

# 🔧 Новые зависимости (для устранения ошибок импорта)
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Request", "RequestInit", "RequestMode", "Response"] }
scraper = "0.18"

# Дополнительно (если используешь async/await в JS)
futures = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
