[package]
name = "sce_parser"
version = "0.3.2"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.104"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.81"
web-sys = { version = "0.3.81", features = [
  "Window", "Response", "Request", "RequestInit", "RequestMode",
  "Headers", "console"
] }

# JSON, парсинг и утилиты
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
scraper = "0.18"

# ✅ Правильная версия getrandom для WebAssembly
getrandom = { version = "0.2.16", features = ["js"] }

# ✅ Rand (для совместимости с getrandom)
rand = { version = "0.8.5", default-features = false, features = ["std", "js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
