[package]
name = "sce_parser"
version = "0.2.2"
edition = "2021"
authors = ["YourName <you@example.com>"]
description = "Steam Card Exchange parser for browser (WASM)"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json", "wasm"] }
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "console"] }
getrandom = { version = "0.3.3", features = ["js", "wasm_js"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.3", features = ["js", "wasm_js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
