name: Build WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust and target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Clean Cargo build cache
        run: cargo clean

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build with wasm-pack
        run: wasm-pack build --target web

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: pkg/
          
