name: Build and Deploy WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Force update getrandom
        run: |
          echo '[patch.crates-io]' >> Cargo.toml
          echo 'getrandom = { version = "0.2.16", features = ["js"] }' >> Cargo.toml
          cat Cargo.toml

      - name: Clean old cache
        run: cargo clean

      - name: Build WebAssembly package
        run: wasm-pack build --target web --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: pkg/
          
